### ISSUE TITLE
Updating with chromedp-gen fails

### ISSUE THREAD

**Issue by wendigo** [knq/chromedp#10]
```
./build.sh
go generate
qtc: 2017/01/28 21:01:41 Compiling *.qtpl template files in directory "templates"
qtc: 2017/01/28 21:01:41 Compiling "templates/domain.qtpl" to "templates/domain.qtpl.go"...
qtc: 2017/01/28 21:01:41 error when parsing file "templates/domain.qtpl": error in "func CommandTemplate(c *internal.Type, d *internal.Domain, domains []*internal.Domain)": error in "if len(c.Parameters) != 0": error in "for _, p := range c.Parameters": error in "if !p.Optional": unexpected tag found after "continue": "end" at file "templates/domain.qtpl", line 24, pos 105, token "end", last line "{% if len(c.Paramete" ... "% continue %}{% end "
main.go:3: running "qtc": exit status 1
```

**Comment by kenshaw** [comment]
Both the versions of quicktemplate and easyjson that I'm using have some minor modifications to them. These are available here:

https://github.com/kenshaw/easyjson
https://github.com/kenshaw/quicktemplate

Please note I am not going to try to maintain these packages; but I will keep them updated. The relevant changes that I have made I have asked to be merged into their master branch via either issues or via pull requests. Fingers crossed they get accepted at some point.

For the record, the versions in my personal repositories have the following differences:

For quicktemplate I enabled the `{% end %}' shorthand, which is not really necessary -- I could easily change the templates so that they do not use the '{% end %}' closing tag, and instead use the {% endif %} or whatever respective closing tag instead.

For easyjson I fixed the documentation and some ordering issues, as easyjson's output previously was inconsistent (it had a map key ordering issue in a couple places). For the record, I will not accept a pull request that does not use a version of easyjson that fixes the output ordering. Otherwise, there will be way too many useless line changes every other commit.

**Comment by wendigo** [comment]
Thx for the clarification! :)
