### ISSUE TITLE
why i need to close any instances of chrome which is already open ?

### ISSUE THREAD

**Issue by AmrAlfoly** [knq/chromedp#116]
if i am loading chrome using a specific profile , why i need to close any instances of chrome which is already opened ?

**Comment by AmrAlfoly** [comment]
don't bother , package support = none

**Comment by kenshaw** [comment]
I'm not sure what your original issue is. If you specify a different user profile directory, it will launch separately. If you use the `chromedp/runner` package to launch, it will generate a temporary directory used, so there should not be an overlap. Also, please note that in order to really be able to answer your question, key information would need to be provided such as version of Chrome, operating system in use, etc.
