### ISSUE TITLE
Unable to set extra http headers for basic authorization

### ISSUE THREAD

**Issue by tbruyelle** [knq/chromedp#122]
I'm pretty sure I'm misusing the library: I'm trying to achieve a basic authorization with chromedp but it seems my extra headers are ignored.

My code: 

```go
err = c.Run(ctx, cdp.Tasks{
    cdp.ActionFunc(func(ctx context.Context, h cdpt.Handler) error {
         x := base64.StdEncoding.EncodeToString([]byte("login:password"))
	 headers := network.Headers{"Authorization": "Basic " + x}
	 return network.SetExtraHTTPHeaders(headers).Do(ctx, h)
    }),
    cdp.Navigate(url), 
    // -> chrome displays me the authentication popup whereas I set the headers.
})
```

What's wrong with this code?
I took inspiration from the `cookie` example https://github.com/knq/chromedp/blob/master/examples/cookie/main.go

**Comment by kenshaw** [comment]
I'm not sure why you wouldn't just use the `http://user:pass@host/` form for basic authentication?

**Comment by kenshaw** [comment]
There's a chance that you can't set that header via the Chrome Debugging Protocol, and that is probably entirely by design. I don't have time to look through the Chrome source tree, but I imagine that's the problem. Regardless, you should be able to specify this in the URL you're passing to `Navigate`, and besides that would be the more "correct" implementation.

**Comment by tbruyelle** [comment]
Thank you for the answer, I'll try. 

ChromeDP is awesome, great work!
