### ISSUE TITLE
KeyAction parameter opts is unused

### ISSUE THREAD

**Issue by mvdan** [knq/chromedp#141]
Raising an issue as I'm not sure if this is on purpose. Could be a bug, since the other funcs receiving options do apply them properly. Found with unparam:

```
cmd/chromedp-gen/internal/types.go:370:44: (*Type).RetNameList - d is unused
cmd/chromedp-gen/internal/types.go:370:55: (*Type).RetNameList - domains is unused
cmd/chromedp-gen/templates/templates/extra.qtpl:7:80: StreamExtraTimestampTemplate - d is unused
cmd/chromedp-gen/templates/util.go:35:23: formatComment - chop always receives ""
input.go:154:29: KeyAction - opts is unused
runner/runner_linux.go:46:13: Rlimit - res is unused
```

The `runner/runner_linux.go` is also a bit suspicious.

**Comment by kenshaw** [comment]
The API was written to be forward compatible. In the past, there were key options such as the "shift" key being applied, and is an artifact from a previous, incorrect implementation of the KeyAction. The API should keep this, as it might change in the future, to specify things like the delay between a key press. I had pulled out the actual application of the opts against the "real" key event call (returned from `kb.Encode`), because for testing I needed it to be a "pure" implementation. This also harks back to the issue that the `chromedp` package itself, is really a high-level implementation, and if people needed more precise control over how the key events get sent, then they should likely call the `kb.Encode` func directly, for the associated string they want to send, and modify the returned parameters, before dispatching them via `.Do()`.
