### ISSUE TITLE
how to know if a new tab was opened ?

### ISSUE THREAD

**Issue by AmrAlfoly** [knq/chromedp#145]
i am using chromedp as a testing tool for my sites and i need to know :
how to know if a new tab was opened ?
and how to close any new tabs and change focus to my old tab

**Comment by smpaq** [comment]
You launch a new tab by creating a new action (cdp.NewTarget) that blocks until the tab is ready. The new target or tab is activated by default by chromedp.

To change focus to a tab, you need to get its ID and use cdp.SetTargetByID. You can also activate a new target by its index if you prefer.

To close a tab, cdp.CloseByID or cdp.CloseByIndex should do the job, but these functions might not work because of [issue #144](https://github.com/knq/chromedp/issues/144)

**Comment by AmrAlfoly** [comment]
that is not what i meant .
if the browser clicks a link and that link opens two tabs 
how can i know how many tabs was opened so i can close the new opened tabs and change focus back to my main tab?

**Comment by korovkinand** [comment]
To know how many targets are opened now you should use something like 
`targets := len(c.ListTargets())`
So you can store a value before clicking a link and compare with a value after

**Comment by AmrAlfoly** [comment]
cool , i tried it and it works
now i need to close the new opened tab and return focus to the old one
how to do that ?

**Comment by korovkinand** [comment]
I created the [issue](https://github.com/knq/chromedp/issues/144) that closing of tabs doesn't work cause corresponding functions aren't implemented. [Solution](https://github.com/knq/chromedp/issues/144#issuecomment-350411865) was suggested in comments, but I haven't tested it yet.

**Comment by weisd** [comment]
so how?

**Comment by weisd** [comment]
so how to do?
