### ISSUE TITLE
How to apply proxy in remote mode

### ISSUE THREAD

**Issue by rinetd** [knq/chromedp#147]
1. 
 `docker run -d -p 9222:9222 --rm --name chrome-headless knqz/chrome-headless`
2. 
```go
c, err := cdp.New(ctxt,
		cdp.WithTargets(
			client.New().WatchPageTargets(ctxt),
		),
		cdp.WithRunnerOptions(
			runner.Proxy(`socks5://127.0.0.1:1080`),
		))
````
proxy is not apply

**Comment by kenshaw** [comment]
Please note that you're going to need to do a lot more configuration of Docker, etc. if you want to use that image with this package. Specifically, you need to make sure that your Docker instance is being launched so that it can actually communicate with that proxy. This is a question on how to use Docker, and as such isn't really a chromedp issue.

**Comment by rinetd** [comment]
i mean how to dynamic change proxy ip in chromedp 
such as  i have 5 http-proxys , how to dynamic replaced by the proxy?

**Comment by kenshaw** [comment]
You can't change the proxy (as far as I'm aware) without restarting your Chrome process.

**Comment by rinetd** [comment]
thank you
