### ISSUE TITLE
Body tag doesn't work as a selector

### ISSUE THREAD

**Issue by Samsimus12** [knq/chromedp#156]
Is there any way to use body as a selector? 

If I use CSS selectors as such: 'body > div > ul > li:nth-of-type(3)' then it will work across the various cdp functions with cdp.ByQuery, but if I just use 'body' it doesn't work. 
Like, for instance, I'm trying to take a screenshot with 'body' as my selector, but it never works. I've tried using just the CaptureScreenshot function but depending on the page sometimes content gets cut off. 

Not sure if this is an issue or not, but I just thought I'd put it out there in case someone had input on it. 

Also, is there anyway to clear the browser history automatically?

**Comment by kenshaw** [comment]
1. You can use XPath via the `ByXPath` selector type instead.  However, I'm not sure if you can just match the `body` element with a CSS selector; that might not be possible (a Chrome limitation). Try with Chrome DevTools -- if you can do it there, it would be identical with `chromedp`.

2. There are two high-level actions: `CaptureScreenshot` (which is just an alias for `page.CaptureScreenshot`) and `Screenshot`. `Screenshot` will capture an element, but only if it is entirely contained on the viewport (otherwise any parts extending past the viewport will not be rendered/captured in the screenshot).

3. Chrome is limited to being able to take a screenshot of only what is currently in the active viewport. There would be quite bit of logic needed to make a genericized version of `Screenshot` that captures the entire "page" (for whatever you want to define as a "page"). And, anyways, it likely would not actually be a correct implementation, as you would need to manually stitch the screenshots together, moving the viewport accordingly, which raises all kinds of questions of "what would be the right behavior" on a myriad number of conditions and edge cases. That kind of logic goes far beyond the aims of the `chromedp` package, and the complexity alone in that implementation I think would warrant a separate package. 

4. Your best bet would be to manually set the viewport to a ridiculously large size (note that the memory consumption will be high!), and attempt to capture only the `body` element using `Screenshot`.

5. I'm not sure what you mean by "automatically" clearing the browser history. Yes, there are programmatic ways to clear the history, please refer to the [Chrome DevTools Protocol documentation](https://chromedevtools.github.io/devtools-protocol/). Take a look at the `CacheStorage` domain, and the `Network.clearBrowserCache` and `Network.clearBrowserCookies` API calls. However, if your intent is to "start over", I would suggest shutting down Chrome instance and restart it with a new profile directory (use the `runner.UserDataDir` option if using the `runner` package to launch Chrome). It's probably worth noting that the the `Network.clear*` APIs probably don't do exactly what you want -- there's all kinds of logic / rules with Chrome that I don't have time to get into (mostly for the fact that the Chromium source tree is constantly changing target, and it requires all kinds of notes/caveats based on whatever version you're running).

**Comment by Samsimus12** [comment]
Thanks for your help, Ken.

I needed to clear my browsing data after certain tasks and this was my solution if anyone else needs to do the same thing:

c.Run(ctxt, network.ClearBrowserCache())
c.Run(ctxt, network.ClearBrowserCookies())
