### ISSUE TITLE
q: How to upload files

### ISSUE THREAD

**Issue by dz0ny** [knq/chromedp#30]
Is there a way to upload a file via form?

**Comment by kenshaw** [comment]
Thanks, actually, for bringing this to my attention. I am not aware of a way, at the moment, that one can send / upload files using the low-level Chrome Debugging Protocol. I'm pulling apart chromedriver now, to see how it goes about accomplishing that. I'll report back here if there is a way, and will likely add a high level action to chromedp to directly support sending a file.

**Comment by kenshaw** [comment]
From what I can tell, so far, from reading the chromedriver source, is that it just does SendKeys on the node with the path to the file to upload. Unfortunately, I'm not able to test this myself at the moment, but will try to do so tomorrow some time.

There's a chance you would need to send a "\n" along with the actual path string to the `SendKeys` action in order to simulate hitting "enter" on a keyboard.

**Comment by dz0ny** [comment]
I was trying to use set attribute value to file filed, but that did not work. Thx for explaining :)

**Comment by kenshaw** [comment]
SetAttribute might be possible, as it calls the underlying protocol directly. But my guess is it wouldn't because its probably getting sent into v8 somewhere, which would (most likeyl) have that disabled. I'm actually working to see if I can figure out how to do this properly now, as part of fixing issues with other unit tests.

**Comment by lucas-clemente** [comment]
Have you figured out a way to do uploads?

I'm trying the code from this [SO answer](http://stackoverflow.com/a/6129464/220918), but it doesn't work (it seems the sendKeys doesn't work):

```
chromedp.WaitVisible("#upload"),
chromedp.SendKeys("#upload", filename),
chromedp.Submit("#upload"),
```

**Comment by kenshaw** [comment]
I have not honestly looked into it, because none of the ways that we're using chromedp requires uploading files. I do apologize, I wish I had more bandwidth to fix these issues but I have limited time.

**Comment by lucas-clemente** [comment]
No worries – and thanks for doing this!

I'll look into it some more, but I guess for our use-case ([quic-go integration tests](https://github.com/lucas-clemente/quic-go)) I guess it'll be easier to just POST from JS instead of uploading.

**Comment by pwaller** [comment]
I just had a go, but likewise could not figure it out. SendKeys does not work for me like it does with Selenium.

I've posted to the [chrome-debugging-protocol google group](https://groups.google.com/d/topic/chrome-debugging-protocol/SUP-4fjp20E/discussion) to ask.

**Comment by pwaller** [comment]
Looks like I [found it](https://github.com/cyrus-and/chrome-remote-interface/issues/164):

> you can use DOM.setFileInputFiles

[`cdp.SetFileInputFiles`](https://github.com/knq/chromedp/blob/869aafc83605fc83718551fe3bfdc797b8e6feee/cdp/dom/dom.go#L1053-L1063).

**Comment by kenshaw** [comment]
Thanks @pwaller that is indeed the API call. I added a simple example (`examples/upload/main.go`) that demonstrates uploading a file. I'll make a point of adding a high-level action to upload a `[]byte` and to pass a simple string. Will keep this issue open for now.

**Comment by kenshaw** [comment]
Added logic to `SendKeys` to recognize `input[type="file"]` nodes in commit df490a30252cd7244aa80c14dd57f83dfdfdee5a. Additionally added high level action `SetUploadFiles` and accompanying unit tests.
