### ISSUE TITLE
unexpected panic

### ISSUE THREAD

**Issue by rikonor** [knq/chromedp#40]
Hi,

I was trying to use `chromedp` along with the Docker based example and had some issues, specifically getting a panic which seem to happen when trying to shut down the client.

This should reproduce the issue:
```
package main

import (
	"context"

	cdp "github.com/knq/chromedp"
	"github.com/knq/chromedp/client"
)

func main() {
	ctx := context.Background()

	// create chrome instance
	c, _ := cdp.New(ctx,
		cdp.WithTargets(client.New().WatchPageTargets(ctx)),
	)

	// shutdown chrome
	c.Shutdown(ctx)
}
```

**Comment by kenshaw** [comment]
Could you provide the actual panic?

**Comment by kenshaw** [comment]
You're ignoring the error returned from `cdp.New`. If you actually check, `c` returned from `cdp.New` is nil.

**Comment by kenshaw** [comment]
The problem here is that you are using the `headless` example. This example assumes you already have a Chrome Debugging Protocol client running on port 9222. You can use `chromedp/runner` or some other way to launch a Chrome process. Also, please checkout the way the `chromedp` package is unit tested. There are fully automated headless examples there using the `Pool` type.

**Comment by rikonor** [comment]
Thank you, I will check the unit tests.

Ignoring the error from `cdp.New` was intentional and only after verifying no error was returned.

I was indeed trying to run it using a headless Chrome instance, using your public docker image:
```
➜  ~ docker run -it -p 9222:9222 --rm --name chrome-headless knqz/chrome-headless
[0313/011426.476607:WARNING:resource_bundle.cc(338)] locale_file_path.empty() for locale
[0313/011426.519486:WARNING:resource_bundle.cc(338)] locale_file_path.empty() for locale
[0313/011426.599263:WARNING:resource_bundle.cc(338)] locale_file_path.empty() for locale
```

Then trying to run the following:
```go
package main

import (
	"context"
	"fmt"
	"log"

	cdp "github.com/knq/chromedp"
	"github.com/knq/chromedp/client"
)

func main() {
	ctx := context.Background()

	// create chrome instance
	cl := client.New()
	fmt.Println("cl", cl)

	tgts := cl.WatchPageTargets(ctx)
	fmt.Println("tgts", tgts)

	c, err := cdp.New(ctx, cdp.WithTargets(tgts))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("c", c)

	// shutdown chrome
	fmt.Println("Attempting to shutdown..")
	c.Shutdown(ctx)
}
```
Causes the following panic:
```
➜  regular go run main.go
cl &{http://localhost:9222/json 100000000 5000000000   {{0 0} 0 0 0 0}}
tgts 0xc4200f58c0
c &{<nil> [] 0xc4200f58c0 0xc4200ba210 [0xc4200ba210] map[bb3bc025-e4ea-429e-a57f-25e7505e240b:0] 0x6a000 0x70de0 0x70df0 {{0 0} 0 0 0 0}}
Attempting to shutdown..

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc535]

goroutine 1 [running]:
panic(0x3d4dc0, 0xc42000c0c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/knq/chromedp/runner.(*Runner).Port(0x0, 0x0)
        /Users/orrikon/workspace/go/src/github.com/knq/chromedp/runner/runner.go:261 +0xb5
github.com/knq/chromedp/runner.(*Runner).Client(0x0, 0x0, 0x0, 0x0, 0x19)
        /Users/orrikon/workspace/go/src/github.com/knq/chromedp/runner/runner.go:281 +0x35
github.com/knq/chromedp/runner.(*Runner).Shutdown(0x0, 0x6301c0, 0xc42007a188, 0x0, 0x0, 0x0, 0x19, 0x0)
        /Users/orrikon/workspace/go/src/github.com/knq/chromedp/runner/runner.go:196 +0x67
github.com/knq/chromedp.(*CDP).Shutdown(0xc4200a6240, 0x6301c0, 0xc42007a188, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/orrikon/workspace/go/src/github.com/knq/chromedp/chromedp.go:156 +0xbe
main.main()
        /Users/orrikon/workspace/go/src/github.com/rikonor/tests/chromedp/regular/main.go:30 +0x438
exit status 2
```

**Comment by kenshaw** [comment]
This is a gotcha on the way that Go deals with types. You need to check the error returned by `chromedp.New()`. It is most likely the `timeout waiting for initial target`. This generally means that the remote client cannot be connected to.

**Comment by rikonor** [comment]
I'm not sure that would help in this case given that from the log I pasted it looks like the error returned from `cdp.New` is nil.

**Comment by kenshaw** [comment]
`Shutdown` should not be called when you are using `chromedp.New` with `WatchTargets`. `Shutdown` is just a shorthand to call the process `runner`'s `Shutdown`.

You will note in the `headless` example that there is no call to `Shutdown`. I'll add a check, however, so that if `CDP.Shutdown` is called, it won't panic.

**Comment by rikonor** [comment]
Ah I see. Thanks for the explanation.

Might be a good idea to elaborate a bit on the role of Runner, Client, etc in the readme. I may have missed any explanation if they already exist, but if not it would be really helpful!

Thanks again,
Or

**Comment by kenshaw** [comment]
I just pushed a simple fix around that so that it won't panic. Yes, the entire project is severely lacking in documentation at the moment. I just haven't had time to really do the write ups necessary. However, I do believe we've done a fairly good job at documenting the actual package code, and GoDoc would be your friend here.

Some brief explanations:

* `runner` is just a simple package to help with launching Chrome instances (ie, processes). 
* `client` is a simple package to deal with the low-level, "wire" parts of Chrome Debugging Protocol (ie, the HTTP / WebSocket stuff).
* `chromedp` is the high level "target manager" code that manages an actual Chrome process via the Chrome Debugging Protocol.
* `cdp`  contains the generated code for the actual Chrome Debugging Protocol domains. Originally, this was called `domains` but I felt that `domains` was too generic of a name, and `cdpdomains` was too long. This package is generated entirely by the `cmd/chromedp-gen` tool, and is fairly well documented on its own.
* `kb` contains mostly generated code for all of the Virtual Keys to use with input actions. This was made into a separate package, so that the `chromed.*` namespace wasn't polluted with the approximate 200+ key definitions.

**Comment by rikonor** [comment]
Neat. Thanks for the explanation!
