### ISSUE TITLE
Can't subscribe to Runtime.consoleAPICalled event

### ISSUE THREAD

**Issue by sandro** [knq/chromedp#41]
I have a page with javascript that logs to the console. When I navigate to the page using `chromdp` with logging enabled, I can see that the `Runtime.consoleAPICalled` event is being fired. I'd like to subscribe to this event, but my naive approach isn't working. Any tips?

```golang
c.Run(ctxt, cdp.ActionFunc(func(z context.Context, h cdptypes.Handler) error {
	ch3 := h.Listen(cdptypes.EventRuntimeConsoleAPICalled)
	go func() {
		x := <-ch3
		fmt.Println("\n\nGOT A THING3", x)
	}()
	return nil
}))
c.Run(ctxt, cdp.Navigate(file))
time.Sleep(time.Second)
```

**Comment by MrSaints** [comment]
I'm using `Listen` as well, and it doesn't look like any events are being fired?

**Comment by MrSaints** [comment]
I've put a pull request in for this (#64).

**Comment by pwaller** [comment]
You might be interested in the discussion in #79. It would be good to know the context you're using the console events in - are you trying to just print them, or react to them in the execution path? If the latter, it is important to understand when and how you want to use the result, so that race conditions (of the form that `go build -race` cannot find) can be avoided. So if you could provide a real world example of the problem you're trying to solve - it would be very useful for getting the design and usage patterns for `Listen` correct.

**Comment by kenshaw** [comment]
This will be fixed in a big rollout coming in the next couple days.
