### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by crackcomm** [knq/chromedp#44]
I think it's caused by `SendKeys` method.

```
panic: runtime error: slice bounds out of range

goroutine 759 [running]:
github.com/knq/chromedp.(*TargetHandler).domEvent(0xc4200a62c0, 0xb391a0, 0xc42052c0c0, 0x892140, 0xc42052ada0)
	/home/pah/ws/go/src/github.com/knq/chromedp/handler.go:604 +0xf69
created by github.com/knq/chromedp.(*TargetHandler).processEvent
	/home/pah/ws/go/src/github.com/knq/chromedp/handler.go:264 +0x323
exit status 2
```

**Comment by kenshaw** [comment]
Could you provide more information on what the API call was that `panic`'d ? It would be helpful if you could provide the actual parameters, as well as what browser (and version) you were using. Also, it would help to know what web page. If you record all the actual output, that would also be helpful. I just looked up the actual point in the code, and it's from the `InlineStyleInvalidated` event being received. So really need more information before I can fix this. 

For the record, all that's needed is a simple length check on `e.NodeIds` on line 602 of `handler.go`. I am hesitant to fix this immediately (obviously better safety checking needs to be done), but I need to first understand what's triggering this. My understanding of that event is that the nodes "should" be passed, if it's not then there's about 10,000 other things that need to be checked, none of which can be done without knowing more about the environment in which `chromedp` was being used, it would be folly to blindly add a check here, as it might end up ignoring what is otherwise an error (either an error in the `chromedp` implementation or otherwise).

**Comment by crackcomm** [comment]
I can't really tell which method it was but I am almost sure it's `SendKeys` which causes it.
The reason it's hard to tell is - it works most of the time on the page and then suddenly panics, I think it's because some old events are being processed with info about nodes which already don't exist.

```
Google Chrome 57.0.2987.98 
```

**Comment by kenshaw** [comment]
Where that event happened can occur at any time. It's one of the events sent when the page changes, specifically when the inline style gets changed. Likely you're using `SendKeys` on a text field or some such, and the CSS style is being changed in response to the keys being sent / the data in the text field changing. I'm reviewing the Chrome domain documentation now, and I believe that I'm handling that event correctly. If you can boil this down into something that's reproducible, I would fix it immediately. I lay awake at night worrying about unknown bugs like this, so this would be #1 priority, if you could help distill it down into something testable/debuggable.

**Comment by crackcomm** [comment]
Go to `google.com` and try:

```Go
chromedp.Tasks{
    chromedp.SetValue(`#lst-ib`, "", chromedp.ByID),
    // I saw it typing few times and crashed
    chromedp.SendKeys(`#lst-ib`, fmt.Sprintf("%s\n", query), chromedp.ByID),
    chromedp.Sleep(time.Second * 2),
    // Do it again and again it will crasah eventually
}
```

**Comment by kenshaw** [comment]
I've added a simple bounds check around that part for now. Please try that and let me know if this at least gets you through the specific issue you're having.

However, if you could help me out with finding a reproducible version of the previous code, I'd greatly appreciate it. I really want to figure out the actual logic that's involved, and sans reading the actual Chrome source code, this becomes almost impossible to do, especially if I do not have the actual HTML page / code that was causing the problem.

**Comment by crackcomm** [comment]
I have already implemented this check and it works fine.

**Comment by crackcomm** [comment]
If it doesn't crash also try doing something like that:

```Go
{
	ctxt, cancel := context.WithTimeout(ctx, time.Second)
	defer cancel()

	var notFoundMessage string
	if err := chrome.Run(ctxt, chromedp.Tasks{
		// Look for "not found" message
		chromedp.Text(`//div[@id="search"]//div[text()[contains(., 'did not match any shopping results')]]`, &notFoundMessage),
	}); err != nil && err != context.DeadlineExceeded {
		return nil, err
	}
}
```

It may be also caused by that, I'm not sure.

**Comment by kenshaw** [comment]
These are all on google.com?

**Comment by crackcomm** [comment]
Yes this was on `google.com`.
