### ISSUE TITLE
How to maximize the window

### ISSUE THREAD

**Issue by hairichuhe** [knq/chromedp#49]
```
var err error

	// create context
	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	// create chrome instance
	c, err := cdp.New(ctxt, cdp.WithLog(log.Printf), cdp.WithRunnerOptions(
		runner.WindowSize(1920, 1080),
	))
	if err != nil {
		log.Fatal(err)
	}
```
this is my code,but it can't maximize the window,i'm not find the maximize window api,how can i maximize window?

**Comment by kenshaw** [comment]
I believe you need to pass the `--start-maximized` cli parameter when starting a Chrome process. Please see here: http://peter.sh/experiments/chromium-command-line-switches/

There is not a flag for this in `chromedp/runner`, as such you can use the `runner.Flag` option: 
```go
	c, err := cdp.New(ctxt, cdp.WithLog(log.Printf), cdp.WithRunnerOptions(
		runner.Flag("start-maximized", true),
	))
```

For the record, there's too many different (and changing) command line options for the versions of Chrome and its headless variants -- which is why there isn't a predefined `runner.CommandLineOption` for every single flag. I've tried to include the most used versions. 

Also of note is that `runner.CommandLineOption` is simply a `func(map[string]interface{}) error` type, and you can pass your own `func` that adds multiple options in one fell swoop, if needed.

**Comment by hairichuhe** [comment]
@kenshaw Thank you very much.
