### ISSUE TITLE
Expiration date timestamp serialization in network.SetCookie is broken

### ISSUE THREAD

**Issue by vially** [knq/chromedp#71]
The [network.SetCookie](https://godoc.org/github.com/knq/chromedp/cdp/network#SetCookie) method seems to be broken.

The issue seems to be the JSON serialization of the [ExpirationDate](https://github.com/knq/chromedp/blob/91303cba34c36d59b7115dd8051297e3b8d6c496/cdp/network/network.go#L410) field of the `SetCookieParams` struct.

According to the DevTools Protocol docs the `expirationDate` parameter given to the [Network.setCookie](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie) method is of type [Network.Timestamp](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Timestamp) which is defined as the number of seconds since epoch but the [current implementation](https://github.com/knq/chromedp/blob/91303cba34c36d59b7115dd8051297e3b8d6c496/cdp/cdp.go#L1507-L1510) seems to serialize it as the number of seconds since boot.

Also, the parameter should be optional but in my tests the `expirationDate` field was always present in the JSON serialization of the `network.setCookie` devtools call even when no value has been set to `SetCookieParams.ExpirationDate` field (I haven't looked into it but I suppose this might have something to do with the Go [time.Time](https://golang.org/pkg/time/#Time) not allowing null values).

**Comment by kenshaw** [comment]
Yes, one of the biggest problems / issues with protocol.json is they have changed the Timestamp implementation a number of times, and documentation is only in the source code. Both of these need independent types then. When I originally wrote the Timestamp stuff, I was trying to make it compatible with different versions of the Chrome Debugging Protocol, but realize that's a fraught affair.

**Comment by kenshaw** [comment]
This is partially fixed now with commit 2f321ca8652f835674ed486d623bfa1009972264 -- I have made it so that `cdp.Timestamp` is a pointer on the generated structs. I will unravel the various timestamp types and convert them all to appropriate types. You should at least be able to call `network.SetCookie` now, but cannot set the proper expiration date. This will be possible after I have created separate Timestamp types for everything.

Please see `examples/cookie/main.go`.
