### ISSUE TITLE
Press down a drop down

### ISSUE THREAD

**Issue by clanstyles** [knq/chromedp#8]
Some javscript frameworks like JQuery have complex drop downs. How would you click them? Example: http://labs.abeautifulsite.net/jquery-dropdown/#1

I've though of two ways, Identify the menu, "send keys", but then how do you press "down" on the arrow keys a few times? The other is X,Y but I'm not sure how you'd calculate the position of the item.

**Comment by clanstyles** [comment]
Here's a few things I've tried.
```
		cdp.SendKeys(`//div[@role='listbox']`, ""),
		cdp.ActionFunc(func(ctx context.Context, h cdptypes.FrameHandler) error {
			for a := 0; a < 6; a++ {
				if err := input.DispatchKeyEvent(input.KeyDown).Do(ctx, h); err != nil {
					return err
				}
			}
			return nil
		}),

`

**Comment by kenshaw** [comment]
For system keys, you need to send the raw key event as well. Look at the current SendKeys implementation.

That said, I think a "KeyDown" and "KeyUp" generic actions would be good, and I'll add that to the code shortly.

**Comment by kenshaw** [comment]
BTW -- the input event type "keyDown" for Chrome refers to sending an event equivalent to a physical keyboard's events for "key down" -- it's not the "down arrow" button.

**Comment by kenshaw** [comment]
Also, typically my experience with chromedp, selenium, and other libraries that do similiar things, it's typically easier to call the javascript on the element instead of trying to send key presses. Keep in mind that even option elements can take click events! I also learned a bit more about how chrome works this morning, and will be revamping a bit of the way the query selectors work, so that they traverse frames properly.

**Comment by clanstyles** [comment]
Depending on the framework, the javascript method is still problematic. There can be data attributes and hidden fields that all need to be updated. 

For "keydown" do you mean like 40 (as in the code for the key on the keyboard)?

**Comment by kenshaw** [comment]
Yes. I understand the potential issues, I'm writing a generic way to send the key presses now. It's just a matter of knowing the right codes. What OS are you running this on?

**Comment by kenshaw** [comment]
I just pushed a commit that doesn't really fix this yet, as it doesn't seem to be synthesizing the event. Please see the updated examples/keys/main.go for how I envision the API working.

**Comment by clanstyles** [comment]
Alright, thanks. I'll start playing with it shortly.

**Comment by kenshaw** [comment]
Update: I had figured out the fix for this a couple days ago, but got caught up in fixing other issues. I should be pushing a big commit set either late today or early tomorrow that fixes this properly. For the record, the update should fix key presses for all the regular navigational keys (arrows, home/end/pageup/pagedown) as well as tabs, backspaces, and enter. The API will be the same, just there are special single unicode characters that will correspond to each of those keys.

**Comment by clanstyles** [comment]
Awesome, thanks for all the hard work @kenshaw! I look forward to testing it!

**Comment by kenshaw** [comment]
Attaching log for posterity.
[cdp-ba7a88bb-fb2f-410a-8a1c-f63fc43f567e.txt](https://github.com/knq/chromedp/files/751992/cdp-ba7a88bb-fb2f-410a-8a1c-f63fc43f567e.txt)

**Comment by kenshaw** [comment]
Please check the updated `examples/keys` -- it correctly should be sending the `kb.ArrowDown` values. Additionally, the other navigation keys (Home/End/etc) should be working "as expected" now.

**Comment by JohnStarich** [comment]
Sorry for reviving an old issue, this issue showed up as a top result in my search. I ran into this problem on a simple dropdown and had trouble getting arrow keys to actually update the option.

My page's dropdown wrapped a normal browser dropdown's styles, but ignored arrow key presses after it opened like this:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1009441/77261526-0d5a4700-6c5d-11ea-907e-68ac42f5c413.png">


For anyone landing here in search of an easy dropdown solution, I selected the correct option with this:
```go
chromedp.SendKeys(`#mydropdown`, "Text label content")
```

This focused on the `select` element and typed out the label. Typing the label chooses the right option _**and**_ fires off the required events for a JS dropdown.
