### ISSUE TITLE
How to handle alert boxes?

### ISSUE THREAD

**Issue by pdemacs** [knq/chromedp#92]
I am trying to login to single sign on box but control never seems to reach there.
In selenium solution is to use driver.switchTo().alert(); is there any way to switch to alert window in chromedp?
This happens before the page loads so there is no way to inspect what is going on.
Problem is same as described on this link
https://sqa.stackexchange.com/questions/20710/not-able-to-use-http-basic-auth-popup-in-selenium-test-case-using-firefox-on-ubu

**Comment by kenshaw** [comment]
Sorry for the late response.

The way the Chrome Debugging Protocol works is that the `Page.javascriptDialogOpening` event is sent notifying the user that it exists. At the moment, there is not a great way for listening for events with `chromedp`, however that will change in the near future. After the event is received, the driving logic needs to respond by sending a `Page.handleJavaScriptDialog` command. You can do this manually for now, if you are able to always expect a dialog to open, the only missing part is how to handle when a dialog pops up in the middle of a task set.

Another approach, is that since you are dealing with a full browser under the hood, you can push any kind of javascript to it, and have it handle the dialog interception for you. You can set your Chrome target to always inject a specified script on page load.

**Comment by lorico** [comment]
Hi, I have the same issue. Is there any "great way" for listening for events now with chromedp ?
I didn't understand precisely how works your proposed - as I don't see the "Page.handleJavaScriptDialog" implemented. Do you have a little snippet of what you were thinking of to help?
Thanks a lot, that's seems a really promising lib!

**Comment by botherder** [comment]
I am also having this issue. I need to programmatically close or disable alerts/dialogs which are preventing me to continue navigation to pages. Would anyone have any suggestion on how to fix this? @kenshaw?

**Comment by nicolascb** [comment]
> Hi, I have the same issue. Is there any "great way" for listening for events now with chromedp ?
> I didn't understand precisely how works your proposed solution - as I don't see the "Page.handleJavaScriptDialog" implemented. Do you have a little snippet of what you were thinking of to help?
> Thanks a lot, that's seems to be a really promising lib!

```go
chromedp.ListenTarget(ctx, func(ev interface{}) {
			if _, ok := ev.(*page.EventJavascriptDialogOpening); ok {
				t := page.HandleJavaScriptDialog(false)
				go func() {
					if err := chromedp.Run(ctx, t); err != nil {
                                                        // handle error
					}

					// ok
				}()
			}
		})

**Comment by abdul-creator** [comment]
Hello, I am trying to close alertbox in chrome but unable to listen and close it. Can someone help ?

**Comment by ZekeLu** [comment]
@abdul-creator Please file a new issue with a demo to show the problem.
