### ISSUE TITLE
Suppress excessive logging

### ISSUE THREAD

**Issue by suntong** [knq/chromedp#93]
How can I suppress the excessive logging? 

I'd say that over 99% of the log output are providing too much details that I don't care at the moment, and hope to suppress all of them. I.e., if I have a simple `cdp.Tasks` of `Navigate`, `WaitVisible`, `SendKeys`, `Click`, I just want to know at which stage the `chromedp` is at the moment, e.g., Waiting for Visible of ..., and WaitVisible finished etc, these kind of very high level of logging that relevant to my `chromedp` script. 

Is that possible? Else, any possibility to tune it down? I.e., of `WithLog`, `WithErrorf`, `WithDebugf`, which one closer to what I'm asking for? Thx.

**Comment by kenshaw** [comment]
You don't need to pass a log function at all when creating the actual `chromedp.CDP` instance. The plan is eventually to make the available logging options better. Since it's just a `func` that is being used, you can wrap / supply any `func` with the same signature and filter the messages as needed.

**Comment by suntong** [comment]
True, but that requires each end user to have inside knowledge of what the logged messages are, what type of them, where do they come from, how to do the proper filter to get to the correct level of logging, etc, etc. 

So I'm still hope that such functionality can be provided someday.

**Comment by stephencheng** [comment]
@kenshaw I have done a clean way in my own case, happy to put up a merge request to implement above required.

Providing below features:

1. provide a option for user to split cdp and app level logs
2. provide log level option, so that cdp internal could use: log.info, log.debug, log.warring ..... etc to categorise different level, user could set the level to higher to avoid seeing lower level unwanted details.

@suntong I agree with @kenshaw , this is not a core thing for cdp, you could easily implement what I mentioned function 1 using this: 	"github.com/op/go-logging"
