### ISSUE TITLE
fitWindow: boolean value expected when using emulation.SetDeviceMetricsOverride

### ISSUE THREAD

**Issue by kmanley** [knq/chromedp#97]
emulation.SetDeviceMetricsOverride results in an error regarding a "fitWindow" parameter. However I see no such parameter anywhere in the codebase.

```
2017/08/02 15:25:43 <- {"id":9,"method":"Emulation.setDeviceMetricsOverride","params":{"width":800,"height":3000,"deviceScaleFactor":1,"mobile":false}}
2017/08/02 15:25:43 -> {"error":{"code":-32602,"message":"Invalid parameters","data":"fitWindow: boolean value expected"},"id":9}
```

Here's the repro case

```go
package main

import (
	"context"
	//"fmt"

	"log"

	cdp "github.com/knq/chromedp"
	cdptypes "github.com/knq/chromedp/cdp"
	"github.com/knq/chromedp/cdp/emulation"
)

func main() {
	var err error

	// create context
	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	// create chrome instance
	c, err := cdp.New(ctxt, cdp.WithLog(log.Printf))
	if err != nil {
		log.Fatal(err)
	}

	err = c.Run(ctxt, setViewportAndScale(800, 3000, 1.0))
	if err != nil {
		log.Fatal(err)
	}
}

func setViewportAndScale(w, h int64, scale float64) cdp.ActionFunc {
	return func(ctxt context.Context, ha cdptypes.Handler) error {
		var err error
		err = emulation.SetDeviceMetricsOverride(800, 3000, 1.0, false).Do(ctxt, ha)
		if err != nil {
			return err
		}
		return nil
	}
}

```

**Comment by kenshaw** [comment]
The `fitWindow` mode / field was removed on July 20th  from the protocol definitions in the Chromium source tree (in commit cc099f72c9fe6f67590e70b2956e27a7b5e7ac38), and subsequently was  removed from `chromedp` on July 22nd in commit b9e4c14157325be092c1c1137edbd584648d8c72. I've modified the `update.sh` script in the `cmd/chromedp-gen` sub-directory so that one can more easily specify a specific Chromium commit/branch:

```sh
# get latest chromedp source and change to chromedp-gen directory
$ go get -u github.com/knq/chromedp
$ cd $GOPATH/src/github.com/chromedp/cmd/chromedp-gen

# update to pre-cc09f72 version of protocol.json -- as of today, my stable version of Chromium on Ubuntu is reporting version 60.0.3112.78:
./update.sh 60.0.3112.78 

# regenerate domain types/commands/events
./build.sh
```

Please note that this project aims to track the Chromium source tree as closely as possible, thus for whatever project you are using this with, you need to pin the `chromedp` version used in a `/vendor/` folder or some such as it is very much dependent on the version of Chrome/headless_shell/etc. being used.

Unfortunately the `protocol.json` changes practically on a weekly basis. As such, there's not a lot I can do to alleviate these kinds of problems. I am thinking of separating the actual low-level wireline protocol / JSON types to a separate repository, but that still wouldn't prevent issues like this from occurring, as you'd need to use a specific version of `chromedp` pinned to the version of the protocol supported by your browser.

**Comment by kmanley** [comment]
Ken, thanks for this detailed response. This is a great project, thank you for making it open source.
